### PR TITLE
Add redux

### PR DESCRIPTION
**Pull request by astroboyReloaded**
- Add Redux Toolkit (npm install react-redux @reduxjs/toolkit).
- Create a directory that will contain all your Redux logic (/src/redux).
- Configure a Redux store (/src/redux/store.js).
- Define a slice of state for books that:
   - Includes an array of books (initial state: empty array).
   - Includes a reducer that adds a book.
   - Includes a reducer that removes a book.
- Define a slice of state for categories that:
   - Includes an array of categories (initial state: empty array).
   - Includes a reducer that checks the status and always returns "Under construction" (the initial state should check to that string).
- Structure application files using a "feature folder" approach and use the [ducks pattern](https://github.com/erikras/ducks-modular-redux) for Redux files.

### CODE REVIEW

**Review by zainsadaqat — COMMENTED** [review]
# ❌ ❌ ❌Invalid Code Review Request ❌ ❌ ❌
# Hello @astroboyReloaded  👋  

## Something went wrong 

### While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

Your Code Review Request is marked as invalid for this reason:

- ### You have submitted a project, where one of the linter is failing. Kindly fix the linter issue. 👍 
Screenshot 2023-06-13 at 12 30 39 AM


Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers, and Happy coding!👏👏👏



Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

**Comment by astroboyReloaded** [comment]
Thank you @zainsadaqat! I apologize. I don't get the error when I run eslint locally, but I will fix it.

**Review by frank1738 — APPROVED** [review]
Hi @astroboyReloaded , 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 
\\


## Highlights

✅ Correct use of Gitflow
✅ No linter error
✅ Actions and Reducers are setup correctly

## Optional suggestions

N/A

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by astroboyReloaded** [comment]
Thank you, @frank1738!

**Pull request merged**
