### PR TITLE
Connect api

### PR DESCRIPTION
**Pull request by astroboyReloaded**
- Make use of the [Bookstore API](https://www.notion.so/Bookstore-API-51ea269061f849118c65c0a53e88a739) as the backend.
- Use [axios](https://axios-http.com/docs/intro) with [createAsyncThunk](https://redux-toolkit.js.org/api/createAsyncThunk) to make HTTP requests.
- **Fetch books** from the **Bookstore API** after the component has rendered.
- Refactor your `addBook` and `removeBook` features to persist your changes in the server.

### CODE REVIEW

**Review by didierganthier — COMMENTED** [review]
Hi @astroboyReloaded ,

While you put in a lot of hard work in this project, unfortunately, I cannot proceed with the review of your code.



## Invalid Code Review Request 🚫

- You have submitted a project where the README doesn't have all the required Table of Contents items and missing the `Getting Started` header in the README body. 📖 🤒 

Your Code Review Request will be marked as invalid in your Dashboard, but don't worry you can always try again! 💪

Cheers and Happy coding!👏👏👏

If you have any questions or need clarification on anything, feel free to leave a comment in the pull request thread and don't forget to tag me so I'll receive the notification.

**Please note**
- To avoid confusion and delays, please do not open a new pull request for re-reviews. Use the same pull request submitted for the first review, unless otherwise instructed.

--------

_Invalid Code Review Request **does not count** towards the code reviews limit._

**Comment by astroboyReloaded** [comment]
Hi, @didierganthier! Thank you for taking the time to review my project.
I have to ask: are you positive these are requirements? The **README** in this project is just as good and has all the same sections as many of my previous projects already approved. Can you double-check this, please? There is really nothing more that I consider important to add to the README for this project.
Regards, @astroboyReloaded (Alejandro Muñoz)

**Comment by didierganthier** [comment]
Make sure that the `Table of Contents` has all the required sections just like the template.

**Review by didierganthier — APPROVED** [review]
Hi @astroboyReloaded ,

Congratulations! 🎉 Your project is complete and ready to be merged! 🚀



## Highlights
- Descriptive PR ✔️ 
- Linters passing ✔️ 
- Correct Gitflow ✔️ 

## Optional Suggestions 💡
- N/A

Cheers, and Happy coding!👏👏👏

If you have any questions or need clarification on anything, feel free to leave a comment in the pull request thread, and don't forget to tag me so I'll receive the notification.

------
As per the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561), you have a limited number of reviews per project. If you feel that the code review was unfair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s). 

Once again, congratulations on completing this project! 🎉

**Pull request merged**
